# Generated by Django 4.2 on 2023-04-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('model_id', models.CharField(db_column='id', max_length=5, primary_key=True, serialize=False)),
                ('vendor', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('RICKSHAW', 'Auto Rickshaw'), ('SEDAN', 'Sedan'), ('SUV', 'Suburban Ultra Vehicle'), ('JEEP', 'Jeep')], help_text='Select Vehicle Type', max_length=50)),
                ('capacity', models.PositiveSmallIntegerField(default=2)),
            ],
        ),
    ]
